name: edge-nns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numba
    - numpy
    - pandas
    - matplotlib
    - pillow
    - jupyter
    - tensorflow
    - qkeras
    - keras
    - tensorflow-model-optimization
    - pot
    - PyYAML
    - scikit-learn
    - tqdm
    - setgpu
    - mplhep
    - opencv-python
    - git+ssh://git@github.com/KastnerRG/fkeras.git#egg=fkeras